name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: docker.pkg.github.com/Suppolyar/nest-js-backend-practice/nest-js-backend-practice
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          tags: develop

